<a href="https://colab.research.google.com/github/vappanna/BerAIML/blob/main/Usage.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

# Load the Usage file
usage_df = pd.read_excel('/content/Usage.xlsx')

# Load the mapping file
mapping_df = pd.read_excel('/content/Install Base Mapping.xlsx')

print("First 5 rows of Usage DataFrame:")
display(usage_df.head())

print("\nFirst 5 rows of Mapping DataFrame:")
display(mapping_df.head())

# Merge the usage_df with mapping_df to get the NewSystemModel
# Perform a left merge to keep all rows from usage_df
usage_df = pd.merge(usage_df, mapping_df,
                    left_on='SYSTEMMODELNAME',
                    right_on='SystemModel',
                    how='left')

# Drop the original SYSTEMMODELNAME column and the temporary SystemModel column from mapping
usage_df.drop(columns=['SYSTEMMODELNAME', 'SystemModel'], inplace=True)

# Rename the NewSystemModel column to SYSTEMMODELNAME, as per the user's request to replace the column name
# If the user literally meant to rename the *new* column to the *old* column name (SYSTEMMODELNAME), it would be:
# usage_df.rename(columns={'NewSystemModel': 'SYSTEMMODELNAME'}, inplace=True)
# However, the request is to 'Replace the SYSTEMMODELNAME with NEWSYSTEMMODEL from mapping file. Replace the column name also'
# This implies the final column should be named NewSystemModel.
# So, the column name 'NewSystemModel' will be kept as is.

print("\nFirst 5 rows of Usage DataFrame after mapping and column replacement:")
display(usage_df.head())

First 5 rows of Usage DataFrame:

,CAPITALREGION,SYSTEMMODELNAME,QUARTER(LOCALPROCEDUREDATE),YEAR(LOCALPROCEDUREDATE),COUNT (*)
0,Asia : China,da Vinci S,1,2015,960
1,Asia : China,da Vinci S,2,2015,1106
2,Asia : China,da Vinci S,3,2015,1210
3,Asia : China,da Vinci S,4,2015,1172
4,Asia : China,da Vinci S,1,2016,1022

First 5 rows of Mapping DataFrame:

       SystemModel NewSystemModel
0         da Vinci        Model 8
1       da Vinci 5        Model 7
2       da Vinci S        Model 6
3      da Vinci Si        Model 5
4  da Vinci SimNow        Model 4

First 5 rows of Usage DataFrame after mapping and column replacement:

,CAPITALREGION,QUARTER(LOCALPROCEDUREDATE),YEAR(LOCALPROCEDUREDATE),COUNT (*),NewSystemModel
0,Asia : China,1,2015,960,Model 6
1,Asia : China,2,2015,1106,Model 6
2,Asia : China,3,2015,1210,Model 6
3,Asia : China,4,2015,1172,Model 6
4,Asia : China,1,2016,1022,Model 6

In [3]:
import pandas as pd

# Load the Usage file
usage_df = pd.read_excel('/content/Usage.xlsx')

# Load the mapping file
mapping_df = pd.read_excel('/content/Install Base Mapping.xlsx')

print("First 5 rows of Usage DataFrame:")
display(usage_df.head())

print("\nFirst 5 rows of Mapping DataFrame:")
display(mapping_df.head())

# Merge the usage_df with mapping_df to get the NewSystemModel
# Perform a left merge to keep all rows from usage_df
usage_df = pd.merge(usage_df, mapping_df,
                    left_on='SYSTEMMODELNAME',
                    right_on='SystemModel',
                    how='left')

# Drop the original SYSTEMMODELNAME column and the temporary SystemModel column from mapping
usage_df.drop(columns=['SYSTEMMODELNAME', 'SystemModel'], inplace=True)

# Rename the NewSystemModel column to SYSTEMMODELNAME, as per the user's request to replace the column name
# If the user literally meant to rename the *new* column to the *old* column name (SYSTEMMODELNAME), it would be:
# usage_df.rename(columns={'NewSystemModel': 'SYSTEMMODELNAME'}, inplace=True)
# However, the request is to 'Replace the SYSTEMMODELNAME with NEWSYSTEMMODEL from mapping file. Replace the column name also'
# This implies the final column should be named NewSystemModel.
# So, the column name 'NewSystemModel' will be kept as is.

print("\nFirst 5 rows of Usage DataFrame after mapping and column replacement:")
display(usage_df.head())

# Save the processed DataFrame to a CSV file
usage_df.to_csv('processed_usage.csv', index=False)
print("\n'processed_usage.csv' has been saved to your Colab environment.")

First 5 rows of Usage DataFrame:

,CAPITALREGION,SYSTEMMODELNAME,QUARTER(LOCALPROCEDUREDATE),YEAR(LOCALPROCEDUREDATE),COUNT (*)
0,Asia : China,da Vinci S,1,2015,960
1,Asia : China,da Vinci S,2,2015,1106
2,Asia : China,da Vinci S,3,2015,1210
3,Asia : China,da Vinci S,4,2015,1172
4,Asia : China,da Vinci S,1,2016,1022

First 5 rows of Mapping DataFrame:

       SystemModel NewSystemModel
0         da Vinci        Model 8
1       da Vinci 5        Model 7
2       da Vinci S        Model 6
3      da Vinci Si        Model 5
4  da Vinci SimNow        Model 4

First 5 rows of Usage DataFrame after mapping and column replacement:

,CAPITALREGION,QUARTER(LOCALPROCEDUREDATE),YEAR(LOCALPROCEDUREDATE),COUNT (*),NewSystemModel
0,Asia : China,1,2015,960,Model 6
1,Asia : China,2,2015,1106,Model 6
2,Asia : China,3,2015,1210,Model 6
3,Asia : China,4,2015,1172,Model 6
4,Asia : China,1,2016,1022,Model 6

'processed_usage.csv' has been saved to your Colab environment.

In [1]:
import pandas as pd

# Load the Usage file
usage_df = pd.read_excel('/content/Usage.xlsx')

# Load the mapping file
mapping_df = pd.read_excel('/content/Install Base Mapping.xlsx')

print("First 5 rows of Usage DataFrame:")
display(usage_df.head())

print("\nFirst 5 rows of Mapping DataFrame:")
display(mapping_df.head())

First 5 rows of Usage DataFrame:

,CAPITALREGION,SYSTEMMODELNAME,QUARTER(LOCALPROCEDUREDATE),YEAR(LOCALPROCEDUREDATE),COUNT (*)
0,Asia : China,da Vinci S,1,2015,960
1,Asia : China,da Vinci S,2,2015,1106
2,Asia : China,da Vinci S,3,2015,1210
3,Asia : China,da Vinci S,4,2015,1172
4,Asia : China,da Vinci S,1,2016,1022

First 5 rows of Mapping DataFrame:

       SystemModel NewSystemModel
0         da Vinci        Model 8
1       da Vinci 5        Model 7
2       da Vinci S        Model 6
3      da Vinci Si        Model 5
4  da Vinci SimNow        Model 4